version: '3.4'

services:
  clientesapv.webapi:
    image: ${PRODUCTION_CANALESELECTRONICOSAPV_REGISTRY}:${PRODUCTION_CLIENTESAPV_TAG_CANDIDATE}
  clientesapv.backgroundtask:
    image: ${PRODUCTION_CANALESELECTRONICOSAPV_REGISTRY}:${PRODUCTION_CLIENTESAPV_BACKGROUNDTASK_TAG_CANDIDATE}