version: '3.4'

services:
  clientesapv.webapi:
    image: ${STAGING_CANALESELECTRONICOSAPV_REGISTRY}:${STAGING_CLIENTESAPV_TAG_CANDIDATE}
  clientesapv.backgroundtask:
    image: ${STAGING_CANALESELECTRONICOSAPV_REGISTRY}:${STAGING_CLIENTESAPV_BACKGROUNDTASK_TAG_CANDIDATE}